# training config
global_config:
    seed: 0

trainer_config:
    max_epochs: 8000
    validation_interval: 2
    early_stopping_patience: 150

data_config:
    train_batch_size: 2
    val_batch_size: 32
    test_batch_size: 32

scheduler_config:
    RLROP_factor: 0.7
    RLROP_patience: 15
    RLROP_cooldown: 15
    RLROP_threshold: 0.001
    EXLR_gamma: 0.999
    warmup_epoch: 25

optimizer_config:
    learning_rate: 0.001
    force_ratio: 0.999
    gradient_clip_val: 10
    ema_decay: 0.99
    weight_decay: 0.0
    
# model_config
model_config:
    rbf: nexpnorm
    max_z: 20
    rbf_trainable: false
    rbound_upper: 10
    z_hidden_dim: 512
    ef_dim: 16
    k_tuple_dim: 512
    block_num: 5
    use_mult_lin: False
    activation_fn_name: silu
    interaction_residual: false



