"1":
  optimizer_config:
    learning_rate: 0.0002

"2":
  model_config:
    interaction_residual: true

"3":
  model_config:
    interaction_residual: true

"0":
  # model_config:
  #   interaction_residual: true
  optimizer_config:
    learning_rate: 0.0003

"12":
  # model_config:
  #   interaction_residual: true
  optimizer_config:
    learning_rate: 0.0003

"13":
  # model_config:
  #   interaction_residual: true
  optimizer_config:
    learning_rate: 0.0003

"14":
  # model_config:
  #   interaction_residual: true
  optimizer_config:
    learning_rate: 0.0003

"15":
  # model_config:
  #   interaction_residual: true
  optimizer_config:
    learning_rate: 0.0003

